# Generated by Django 5.2.3 on 2025-06-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_drug_order_orderitem_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
